import { Tenant, Category, Product, Coupon, LoyaltyReward, AIInsight, Order } from '@/types';

export const INITIAL_TENANT: Tenant = {
  id: 'tenant-sos-lanches-01',
  name: 'SOS.LANCHES Delivery',
  slug: 'sos-lanches-londrina',
  slogan: 'O verdadeiro S.O.S. da sua fome em Londrina!',
  logoUrl: '/sos_lanches_logo.jpg',
  primaryColor: '#E53935',
  secondaryColor: '#FFC107',
  minOrderValue: 20.0,
  defaultFee: 7.0,
  avgDeliveryTime: '30 - 45 min',
  whatsappNumber: '5543999887766',
  address: 'Av. Higienópolis, 1200 - Centro',
  city: 'Londrina',
  state: 'PR',
};

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-combos',
    tenantId: 'tenant-sos-lanches-01',
    name: 'Combos S.O.S.',
    slug: 'combos-sos',
    icon: 'Flame',
    image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f6?auto=format&fit=crop&w=600&q=80',
    orderIndex: 1,
    active: true,
  },
  {
    id: 'cat-dogs',
    tenantId: 'tenant-sos-lanches-01',
    name: 'Dogs Tradicionais & Especiais',
    slug: 'dogs',
    icon: 'Utensils',
    image: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=600&q=80',
    orderIndex: 2,
    active: true,
  },
  {
    id: 'cat-prensados',
    tenantId: 'tenant-sos-lanches-01',
    name: 'Lanches Prensados',
    slug: 'lanches-prensados',
    icon: 'HamBurger',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    orderIndex: 3,
    active: true,
  },
  {
    id: 'cat-brasa',
    tenantId: 'tenant-sos-lanches-01',
    name: 'Burguers na Brasa 180g',
    slug: 'burguers-na-brasa',
    icon: 'Beef',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80',
    orderIndex: 4,
    active: true,
  },
  {
    id: 'cat-porcoes',
    tenantId: 'tenant-sos-lanches-01',
    name: 'Porções & Acompanhamentos',
    slug: 'porcoes',
    icon: 'Utensils',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80',
    orderIndex: 5,
    active: true,
  },
  {
    id: 'cat-cervejas',
    tenantId: 'tenant-sos-lanches-01',
    name: 'Cervejas Trincando & Bebidas',
    slug: 'cervejas-e-bebidas',
    icon: 'CupSoda',
    image: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&w=600&q=80',
    orderIndex: 6,
    active: true,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-combo-sos-brasa',
    tenantId: 'tenant-sos-lanches-01',
    categoryId: 'cat-combos',
    name: 'Combo S.O.S. Brasa + Batata + Cerveja/Refri',
    description: '1 S.O.S. Burguer na Brasa 180g + Porção Média de Batata Frita Crocante + 1 Cerveja Long Neck Trincando ou Refrigerante Lata.',
    price: 46.90,
    promoPrice: 38.90,
    image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f6?auto=format&fit=crop&w=800&q=80',
    isPromo: true,
    isBestSeller: true,
    isNew: false,
    ingredients: ['Pão Brioche', 'Hambúrguer 180g Assado na Brasa', 'Cheddar Cremoso', 'Tiras de Bacon Crocante', 'Batata Frita', 'Cerveja Long Neck ou Refri'],
    nutritionalInfo: 'Calorias: ~1050 kcal',
    prepTimeMinutes: 20,
    active: true,
    stockCount: 60,
    optionGroups: [
      {
        id: 'og-pao-sos',
        name: 'Escolha o Pão',
        minSelect: 1,
        maxSelect: 1,
        required: true,
        options: [
          { id: 'opt-pao-brioche', name: 'Brioche Tostado na Manteiga', price: 0 },
          { id: 'opt-pao-australiano', name: 'Pão Australiano', price: 2.0 },
          { id: 'opt-pao-prensado', name: 'Pão de Lanche Prensado', price: 0 },
        ],
      },
      {
        id: 'og-bebida-sos',
        name: 'Escolha sua Bebida',
        minSelect: 1,
        maxSelect: 1,
        required: true,
        options: [
          { id: 'opt-beb-coca', name: 'Coca-Cola 350ml Lata', price: 0 },
          { id: 'opt-beb-heineken', name: 'Cerveja Long Neck Heineken 330ml (Gelada)', price: 3.5 },
          { id: 'opt-beb-guarana', name: 'Guaraná Antarctica 350ml', price: 0 },
        ],
      },
      {
        id: 'og-extras-sos',
        name: 'Adicionais S.O.S.',
        minSelect: 0,
        maxSelect: 4,
        required: false,
        options: [
          { id: 'opt-ex-frango', name: 'Porção Extra de Frango Desfiado Temperado', price: 5.0 },
          { id: 'opt-ex-bacon', name: 'Bacon Defumado Duplo', price: 4.5 },
          { id: 'opt-ex-catupiry', name: 'Catupiry Original', price: 3.5 },
          { id: 'opt-ex-maio', name: 'Maionese Especial da Casa 50ml', price: 3.0 },
        ],
      },
    ],
  },
  {
    id: 'prod-dog-especial-frango',
    tenantId: 'tenant-sos-lanches-01',
    categoryId: 'cat-dogs',
    name: 'Dog Especial S.O.S. Frango & Bacon',
    description: 'Pão macio, 2 salsichas suculentas, generosa camada de frango desfiado temperado na chapa, bacon crocante, milho, vinagrete, milho, batata palha e maionese verde artesanal.',
    price: 26.90,
    promoPrice: 22.90,
    image: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=800&q=80',
    isPromo: true,
    isBestSeller: true,
    isNew: false,
    ingredients: ['Pão de Dog', '2x Salsichas Sadia', 'Frango Desfiado', 'Bacon Crispy', 'Milho', 'Batata Palha', 'Maionese da Casa', 'Catchup e Mostarda'],
    prepTimeMinutes: 15,
    active: true,
    stockCount: 100,
  },
  {
    id: 'prod-xbacon-prensado',
    tenantId: 'tenant-sos-lanches-01',
    categoryId: 'cat-prensados',
    name: 'X-Bacon Prensado Tradicional Londrina',
    description: 'O clássico prensado de Londrina! Hambúrguer artesanal, queijo derretido, bastante bacon bem fritinho, presunto, alface fresca, tomate e prensado na chapa na medida certa.',
    price: 29.90,
    promoPrice: null,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    isPromo: false,
    isBestSeller: true,
    isNew: false,
    ingredients: ['Pão Prensado', 'Hambúrguer Artesanal', 'Queijo Muçarela', 'Presunto', 'Bacon Frito', 'Alface', 'Tomate', 'Maionese'],
    prepTimeMinutes: 18,
    active: true,
    stockCount: 120,
  },
  {
    id: 'prod-burguer-brasa-180g',
    tenantId: 'tenant-sos-lanches-01',
    categoryId: 'cat-brasa',
    name: 'Burguer na Brasa S.O.S. 180g (Suculento)',
    description: 'Hambúrguer 180g assado na grelha com aroma inconfundível de fumaça e brasa, cheddar duplo derretido, cebola roxa assada e molho barbecue artesanal.',
    price: 35.90,
    promoPrice: null,
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80',
    isPromo: false,
    isBestSeller: true,
    isNew: true,
    ingredients: ['Blend 180g na Brasa', 'Pão Brioche', 'Cheddar Fatiado', 'Cebola Roxa na Grelha', 'Molho Barbecue Defumado'],
    prepTimeMinutes: 22,
    active: true,
    stockCount: 80,
  },
  {
    id: 'prod-batata-cheddar-bacon',
    tenantId: 'tenant-sos-lanches-01',
    categoryId: 'cat-porcoes',
    name: 'Porção Batata Suprema Cheddar & Bacon (400g)',
    description: 'Batata frita crocante dourada coberta com queijo cheddar cremoso aquecido e bastante farofa de bacon defumado.',
    price: 27.90,
    promoPrice: 24.90,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=80',
    isPromo: true,
    isBestSeller: true,
    isNew: false,
    ingredients: ['Batata Palito', 'Cheddar Melt', 'Bacon Crispy'],
    prepTimeMinutes: 15,
    active: true,
    stockCount: 150,
  },
  {
    id: 'prod-longneck-heineken',
    tenantId: 'tenant-sos-lanches-01',
    categoryId: 'cat-cervejas',
    name: 'Cerveja Long Neck Heineken 330ml (Estupidamente Gelada)',
    description: 'Garrafa Long Neck 330ml entregue na temperatura ideal para acompanhar seu lanche ou dog.',
    price: 11.90,
    promoPrice: 9.90,
    image: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&w=800&q=80',
    isPromo: true,
    isBestSeller: true,
    isNew: false,
    ingredients: ['Cerveja Pilsen Heineken 330ml'],
    prepTimeMinutes: 5,
    active: true,
    stockCount: 200,
  },
];

export const MOCK_COUPONS: Coupon[] = [
  {
    id: 'coup-1',
    code: 'SOS10',
    discountType: 'PERCENTAGE',
    discountValue: 10,
    minOrderValue: 30.0,
    validUntil: '2026-12-31',
    active: true,
  },
  {
    id: 'coup-2',
    code: 'FRETEGRATIS',
    discountType: 'FREE_DELIVERY',
    discountValue: 100,
    minOrderValue: 45.0,
    validUntil: '2026-12-31',
    active: true,
  },
  {
    id: 'coup-3',
    code: 'LONDRINAFOME',
    discountType: 'FIXED',
    discountValue: 7.0,
    minOrderValue: 25.0,
    validUntil: '2026-12-31',
    active: true,
  },
];

export const MOCK_LOYALTY_REWARDS: LoyaltyReward[] = [
  {
    id: 'rew-1',
    name: 'Refrigerante Lata 350ml',
    pointsCost: 90,
    rewardType: 'Bebida Grátis',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'rew-2',
    name: 'Porção Média de Batata Frita',
    pointsCost: 180,
    rewardType: 'Acompanhamento',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'rew-3',
    name: 'Dog Simples Tradicional',
    pointsCost: 250,
    rewardType: 'Lanche Grátis',
    image: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=400&q=80',
  },
];

export const MOCK_AI_INSIGHTS: AIInsight[] = [
  {
    id: 'ai-1',
    type: 'DEMAND',
    title: 'Previsão de Alta nos Lanches Prensados na Sexta-Feira',
    message: 'Previsão de alta de +38% nos pedidos de X-Bacon Prensado e Dogs das 19h às 23h. Recomendado reforçar estoque de pães e salsichas.',
    actionText: 'Ajustar Estoque da Cozinha',
    status: 'NEW',
    createdAt: 'Há 15 min',
  },
  {
    id: 'ai-2',
    type: 'PROMOTION',
    title: 'Cervejas Trincando vendem 35% mais em Combos',
    message: 'Clientes da Região Norte adicionam Long Necks com frequência quando há desconto no combo com Burguers na Brasa.',
    actionText: 'Criar Combo Cerveja + Burguer',
    status: 'NEW',
    createdAt: 'Há 1 hora',
  },
  {
    id: 'ai-3',
    type: 'CUSTOMER_RETENTION',
    title: '45 clientes do Centro e Gleba inativos há 25 dias',
    message: 'Dispare notificação WhatsApp com cupom SOS10 para atrair esses clientes para a janta de hoje.',
    actionText: 'Disparar WhatsApp Marketing',
    status: 'NEW',
    createdAt: 'Há 2 horas',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-9102',
    tenantId: 'tenant-sos-lanches-01',
    customerName: 'Rodrigo Martins',
    customerPhone: '(43) 99123-4567',
    customerCpf: '123.456.789-00',
    orderType: 'DELIVERY',
    status: 'PREPARING',
    deliveryAddress: 'Rua Sergipe',
    number: '450',
    neighborhood: 'Centro',
    zipCode: '86010-000',
    reference: 'Próximo ao Calçadão',
    paymentMethod: 'PIX',
    subtotal: 38.90,
    deliveryFee: 7.00,
    discount: 5.00,
    total: 40.90,
    notes: 'Favor caprichar na maionese artesanal verde!',
    createdAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'item-101',
        productId: 'prod-combo-sos-brasa',
        productName: 'Combo S.O.S. Brasa + Batata + Cerveja/Refri',
        unitPrice: 38.90,
        quantity: 1,
        notes: 'Pão Brioche e Heineken Long Neck',
        totalPrice: 38.90,
        options: [
          { groupName: 'Escolha o Pão', optionName: 'Brioche Tostado na Manteiga', optionPrice: 0 },
          { groupName: 'Escolha sua Bebida', optionName: 'Cerveja Long Neck Heineken 330ml (Gelada)', optionPrice: 3.5 },
        ],
      },
    ],
  },
  {
    id: 'ORD-9103',
    tenantId: 'tenant-sos-lanches-01',
    customerName: 'Juliana Kozloski',
    customerPhone: '(43) 99876-5432',
    orderType: 'DELIVERY',
    status: 'NEW',
    deliveryAddress: 'Av. Ayrton Senna da Silva',
    number: '800',
    neighborhood: 'Gleba Palhano',
    zipCode: '86050-460',
    reference: 'Apto 1202 - Bloco B',
    paymentMethod: 'CREDIT_CARD',
    subtotal: 52.80,
    deliveryFee: 9.00,
    discount: 0,
    total: 61.80,
    notes: 'Interfonar ao chegar.',
    createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'item-102',
        productId: 'prod-dog-especial-frango',
        productName: 'Dog Especial S.O.S. Frango & Bacon',
        unitPrice: 22.90,
        quantity: 1,
        notes: '',
        totalPrice: 22.90,
        options: [],
      },
      {
        id: 'item-103',
        productId: 'prod-xbacon-prensado',
        productName: 'X-Bacon Prensado Tradicional Londrina',
        unitPrice: 29.90,
        quantity: 1,
        notes: '',
        totalPrice: 29.90,
        options: [],
      },
    ],
  },
];
